// Badge types
export type BadgeCategory = 'Blockchain' | 'Wallet' | 'Mining' | 'Staking' | 'Thringlet' | 'System';
export type BadgeRarity = 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary' | 'Mythic';

// Badge interface
export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: BadgeCategory;
  rarity: BadgeRarity;
  criteria: string;
  experience: number;
  secret?: boolean;
  locked?: boolean;
  progress?: number;
  progressMax?: number;
  completedAt?: number | null;
  color?: string;
}

// Badge registry - All available badges in the system
export const badgeRegistry: Badge[] = [
  // System Badges
  {
    id: 'genesis_node',
    name: 'Genesis Node',
    description: 'You joined the PVX network as an early adopter.',
    icon: 'Award',
    category: 'System',
    rarity: 'Common',
    criteria: 'Create a PVX wallet',
    experience: 50,
    color: '#3b82f6',
  },
  {
    id: 'explorer',
    name: 'Interface Explorer',
    description: 'Visited all main sections of the PVX interface.',
    icon: 'Compass',
    category: 'System',
    rarity: 'Common',
    criteria: 'Visit all main pages of the application',
    experience: 100,
    progressMax: 5,
    progress: 0,
    color: '#3b82f6',
  },
  {
    id: 'power_user',
    name: 'Power User',
    description: 'You\'ve become proficient with the PVX system.',
    icon: 'Power',
    category: 'System',
    rarity: 'Uncommon',
    criteria: 'Complete 10 different actions on the platform',
    experience: 200,
    progressMax: 10,
    progress: 0,
    color: '#22c55e',
  },
  
  // Wallet Badges
  {
    id: 'wallet_creation',
    name: 'Digital Identity',
    description: 'Created your first PVX wallet.',
    icon: 'Wallet',
    category: 'Wallet',
    rarity: 'Common',
    criteria: 'Create a PVX wallet',
    experience: 100,
    color: '#3b82f6',
  },
  {
    id: 'first_transaction',
    name: 'First Transaction',
    description: 'Sent your first transaction on the PVX network.',
    icon: 'ArrowRightLeft',
    category: 'Wallet',
    rarity: 'Common',
    criteria: 'Send a transaction',
    experience: 100,
    color: '#3b82f6',
  },
  {
    id: 'hodler',
    name: 'Diamond Hands',
    description: 'Held at least 1000 PVX for 7 days.',
    icon: 'Diamond',
    category: 'Wallet',
    rarity: 'Uncommon',
    criteria: 'Hold 1000 PVX for 7 days',
    experience: 250,
    color: '#22c55e',
  },
  {
    id: 'crypto_whale',
    name: 'Crypto Whale',
    description: 'Accumulated over 100,000 PVX in your wallet.',
    icon: 'Trophy',
    category: 'Wallet',
    rarity: 'Epic',
    criteria: 'Have 100,000 PVX in your wallet',
    experience: 1000,
    color: '#a855f7',
  },
  
  // Mining Badges
  {
    id: 'first_block',
    name: 'Block Pioneer',
    description: 'Mined your first block on the PVX blockchain.',
    icon: 'Pickaxe',
    category: 'Mining',
    rarity: 'Common',
    criteria: 'Mine your first block',
    experience: 200,
    color: '#3b82f6',
  },
  {
    id: 'mining_streak',
    name: 'Consistent Miner',
    description: 'Mined blocks for 5 consecutive days.',
    icon: 'Timer',
    category: 'Mining',
    rarity: 'Uncommon',
    criteria: 'Mine blocks for 5 consecutive days',
    experience: 300,
    progressMax: 5,
    progress: 0,
    color: '#22c55e',
  },
  {
    id: 'block_master',
    name: 'Block Master',
    description: 'Mined 100 blocks on the PVX network.',
    icon: 'Cube',
    category: 'Mining',
    rarity: 'Rare',
    criteria: 'Mine 100 blocks',
    experience: 500,
    progressMax: 100,
    progress: 0,
    color: '#3b82f6',
  },
  {
    id: 'hash_legend',
    name: 'Hash Legend',
    description: 'Achieved a remarkable 1000 blocks mined.',
    icon: 'Trophy',
    category: 'Mining',
    rarity: 'Legendary',
    criteria: 'Mine 1000 blocks',
    experience: 2000,
    progressMax: 1000,
    progress: 0,
    color: '#eab308',
  },
  
  // Staking Badges
  {
    id: 'first_stake',
    name: 'Stake Initiate',
    description: 'Made your first stake in the PVX network.',
    icon: 'Lock',
    category: 'Staking',
    rarity: 'Common',
    criteria: 'Make your first stake',
    experience: 150,
    color: '#3b82f6',
  },
  {
    id: 'stake_master',
    name: 'Stake Master',
    description: 'Staked over 50,000 PVX tokens.',
    icon: 'BarChart',
    category: 'Staking',
    rarity: 'Rare',
    criteria: 'Stake 50,000 PVX',
    experience: 600,
    color: '#0ea5e9',
  },
  {
    id: 'long_term_holder',
    name: 'Long-Term Holder',
    description: 'Maintained a stake for over 30 days.',
    icon: 'Clock',
    category: 'Staking',
    rarity: 'Epic',
    criteria: 'Maintain a stake for 30 days',
    experience: 1000,
    progressMax: 30,
    progress: 0,
    color: '#a855f7',
  },
  
  // Blockchain Badges
  {
    id: 'blockchain_scholar',
    name: 'Blockchain Scholar',
    description: 'Demonstrated understanding of blockchain technology.',
    icon: 'GraduationCap',
    category: 'Blockchain',
    rarity: 'Uncommon',
    criteria: 'Complete the blockchain tutorial',
    experience: 200,
    progressMax: 5,
    progress: 0,
    color: '#22c55e',
  },
  {
    id: 'code_reviewer',
    name: 'Code Reviewer',
    description: 'Examined the PVX source code and understood its operation.',
    icon: 'FileCode',
    category: 'Blockchain',
    rarity: 'Rare',
    criteria: 'Review the PVX source code documentation',
    experience: 500,
    color: '#0ea5e9',
  },
  {
    id: 'zk_master',
    name: 'Zero-Knowledge Master',
    description: 'Became proficient with zero-knowledge cryptography principles.',
    icon: 'Shield',
    category: 'Blockchain',
    rarity: 'Epic',
    criteria: 'Complete all ZK cryptography lessons',
    experience: 1000,
    progressMax: 7,
    progress: 0,
    color: '#a855f7',
  },
  
  // Thringlet Badges
  {
    id: 'thringlet_friend',
    name: 'Thringlet Friend',
    description: 'Bonded with your first Thringlet companion.',
    icon: 'Heart',
    category: 'Thringlet',
    rarity: 'Common',
    criteria: 'Interact with a Thringlet 10 times',
    experience: 150,
    progressMax: 10,
    progress: 0,
    color: '#3b82f6',
  },
  {
    id: 'emotion_master',
    name: 'Emotion Master',
    description: 'Experienced all emotional states with your Thringlet.',
    icon: 'Smile',
    category: 'Thringlet',
    rarity: 'Rare',
    criteria: 'Experience all Thringlet emotional states',
    experience: 500,
    progressMax: 6,
    progress: 0,
    color: '#0ea5e9',
  },
  {
    id: 'fusion_pioneer',
    name: 'Fusion Pioneer',
    description: 'Successfully fused two Thringlets to create a new entity.',
    icon: 'Atom',
    category: 'Thringlet',
    rarity: 'Epic',
    criteria: 'Complete a Thringlet fusion',
    experience: 800,
    color: '#a855f7',
  },
  {
    id: 'thringlet_master',
    name: 'Thringlet Master',
    description: 'Collected and interacted with all Thringlet types.',
    icon: 'Crown',
    category: 'Thringlet',
    rarity: 'Legendary',
    criteria: 'Collect all Thringlet types',
    experience: 2000,
    progressMax: 8,
    progress: 0,
    color: '#eab308',
  },
  
  // Secret Badges
  {
    id: 'easter_egg_hunter',
    name: 'Easter Egg Hunter',
    description: 'Found a hidden feature in the PVX interface.',
    icon: 'Search',
    category: 'System',
    rarity: 'Rare',
    criteria: 'Find a hidden feature',
    experience: 300,
    secret: true,
    color: '#0ea5e9',
  },
  {
    id: 'lucky_miner',
    name: 'Lucky Miner',
    description: 'Mined a block with a remarkably low probability.',
    icon: 'Dices',
    category: 'Mining',
    rarity: 'Epic',
    criteria: 'Mine a block with a 1 in 1000 chance',
    experience: 1000,
    secret: true,
    color: '#a855f7',
  },
  {
    id: 'thringlet_whisperer',
    name: 'Thringlet Whisperer',
    description: 'Discovered a deeply hidden Thringlet secret.',
    icon: 'Sparkles',
    category: 'Thringlet',
    rarity: 'Mythic',
    criteria: 'Discover the deepest Thringlet secret',
    experience: 3000,
    secret: true,
    color: '#ec4899',
  }
];